import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import Creator from "@/components/Creator";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "ApkClub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
        <link rel="preconnect" href="//fdn.fontcdn.ir" />
        <link rel="preconnect" href="//v1.fontapi.ir" />
        <link href="https://v1.fontapi.ir/css/VazirFD" rel="stylesheet" />
        <link href="https://fonts.cdnfonts.com/css/iranyekan" rel="stylesheet" />
        <meta name="theme-color" content="#43A047" />
      </head>
      <body style={{fontFamily: 'Vazir FD'}}>
        <Navbar />
        {children}
        <Footer />
        <Creator />
      </body>
    </html>
  );
}
